### ISSUE TITLE
Better dropzone

### ISSUE THREAD

**Issue by pash90** [BlueChilli/ChilliSource.Web.Forms#92]
The current implementation of drop zone is buggy, in JS and very fragile. Following are the enhancements we are implementing:

- [ ] Convert to TypeScript
- [ ] Support single as well as multiple file upload
- [ ] Allow user customisation for UI after the files are dropped onto it

If you would like to add/suggest more, you can add a comment here

**Comment by fuckfuckbla** [comment]
[**__**](url)
